language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t theloner/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true theloner/docker-react npm run test